### ISSUE TITLE
Logo override overrides logo text too

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/Sphinx-TUDelft-theme#2]
The logo override now also overrides the sphinx logo provided by the extension:
�[91mWARNING: unknown config value 'logo' in override, ignoring�[39;49;00m, https://github.com/TeachBooks/bridging_mechanics/actions/runs/12198438093/job/34030183865#step:10:38

Visible in the built book: compare this one: https://teachbooks.io/mechanics-BSc/2024-assignment1/intro.html to this: https://teachbooks.io/mechanics-BSc/intro.html. While the second has logo: text: in the config https://github.com/TeachBooks/mechanics-BSc/blob/main/book/_config.yml

**Comment by douden** [comment]
Problem originates from unsafe setting of a dictionary. Going to be fixed some point in the future.

**Comment by douden** [comment]
@Tom-van-Woudenberg : Could you test the possible fix using _v0.1.4_ ?

**Comment by Tom-van-Woudenberg** [comment]
Doesn't work:
here with default tud options: https://teachbooks.io/bridging_mechanics/2024/intro.html --> text is not shown
here with `tud_change_logo: False` https://teachbooks.io/bridging_mechanics/test_logo/intro.html --> text is visible

This is for this repo: https://github.com/TeachBooks/bridging_mechanics. branch 2024 and test_logo

**Comment by douden** [comment]
Should be fixed now
